In [2]:
import pandas as pd

数据：648个用户的5031条购票记录

In [6]:
"""
trade_record = pd.read_csv("./data/trade_record.csv")
trade_valid = trade_record[trade_record["status"] == 11]
trade_valid.drop(["status"], axis=1)
trade_valid.to_csv("./data/trade_valid.csv", index=False)
"""

In [16]:
data = pd.read_csv("./data/trade_valid.csv")

In [17]:
data

,phone,order_id,price,time,status,start,stop
0,13016089516,4201707041824363786,300,2017/7/4 18:24,11,216,210
1,13016089516,4201707091450427038,200,2017/7/9 14:50,11,216,218
2,13016089516,4201707091748057253,400,2017/7/9 17:48,11,218,210
3,13016089516,4201707092008567391,300,2017/7/9 20:08,11,215,210
4,13016089516,4201707131051370033,600,2017/7/13 10:51,11,215,410
5,13016089516,4201707132159260564,300,2017/7/13 21:59,11,210,215
6,13016089516,4201707141253090863,300,2017/7/14 12:53,11,215,510
7,13016089516,4201707141752321129,300,2017/7/14 17:52,11,510,506
8,13016089516,4201707151141141562,300,2017/7/15 11:41,11,215,210
9,13016089516,4201707151616131739,300,2017/7/15 16:16,11,210,215
10,13016089516,4201707161503192485,200,2017/7/16 15:03,11,214,215
11,13016089516,4201707171138503122,300,2017/7/17 11:38,11,215,210
12,13016089516,4201707171932053542,300,2017/7/17 19:32,11,210,215
13,13016089516,4201707210812166337,300,2017/7/21 8:12,11,215,211
14,13016089516,4201707211615516708,300,2017/7/21 16:15,11,611,215
15,13016089516,4201707220851037139,300,2017/7/22 8:51,11,215,211
16,13016089516,4201707222213507942,300,2017/7/22 22:13,11,210,215
17,13016089516,4201707241500409252,300,2017/7/24 15:00,11,215,608
18,13016089516,4201707261410281033,300,2017/7/26 14:10,11,215,211
19,13016089516,4201707261711471223,500,2017/7/26 17:11,11,408,215
20,13016089516,4201707271710291987,200,2017/7/27 17:10,11,214,215
21,13016089516,4201708021003003663,300,2017/8/2 10:03,11,215,210
22,13016089516,4201708081937450138,300,2017/8/8 19:37,11,305,109
23,13022033307,4201707021838292655,300,2017/7/2 18:38,11,216,105
24,13022033307,4201707070839035164,400,2017/7/7 8:39,11,216,513
25,13022033307,4201707071937295591,200,2017/7/7 19:37,11,513,303
26,13022033307,4201707200841055514,400,2017/7/20 8:41,11,216,513
27,13022033307,4201708091852589427,400,2017/8/9 18:52,11,514,216
28,13046202915,4201708130932182781,1200,2017/8/13 9:32,11,6008,420
29,13046202915,4201708131829419032,1100,2017/8/13 18:29,11,420,3007
...,...,...,...,...,...,...,...
5001,18925610291,4201707311130145105,700,2017/7/31 11:30,11,631,241
5002,18925610291,4201707311540316926,600,2017/7/31 15:40,11,209,524
5003,18925610291,4201708081648037826,600,2017/8/8 16:48,11,524,507
5004,18925610291,4201708082053320855,700,2017/8/8 20:53,11,506,524
5005,18925610291,4201708101636137559,600,2017/8/10 16:36,11,524,109
5006,18925610291,4201708101944289924,300,2017/8/10 19:44,11,109,303
5007,18925948821,4201708011829098829,200,2017/8/1 18:29,11,6008,6011
5008,18925948821,4201708011932489697,200,2017/8/1 19:32,11,6011,6008
5009,18925948821,4201708032037299757,200,2017/8/3 20:37,11,6008,6007
5010,18925948821,4201708041727577495,200,2017/8/4 17:27,11,6008,6011
5011,18925948821,4201708041923009183,200,2017/8/4 19:23,11,6011,6008
5012,18925948821,4201708121655537293,200,2017/8/12 16:55,11,6011,6008
5013,18925948821,4201708141210385403,200,2017/8/14 12:10,11,6011,6008
5014,18925948821,4201708172111480306,200,2017/8/17 21:11,11,6008,6011
5015,18925948821,4201708172159110661,200,2017/8/17 21:59,11,6011,6008
5016,18925948821,4201708211141495490,700,2017/8/21 11:41,11,6007,408
5017,18925948821,4201708211651078540,500,2017/8/21 16:51,11,108,517
5018,18925948821,4201708221422346671,200,2017/8/22 14:22,11,6011,6008
5019,18925948821,4201708221941330292,500,2017/8/22 19:41,11,106,6008
5020,18925948821,4201708250726339185,600,2017/8/25 7:26,11,6008,108
5021,18925948821,4201708251756456097,500,2017/8/25 17:56,11,108,6011
5022,18925948821,4201708252140408674,200,2017/8/25 21:40,11,6011,6008
5023,18925948821,4201708261217592620,200,2017/8/26 12:17,11,6008,6011
5024,18925948821,4201708280702307711,600,2017/8/28 7:02,11,6008,108
5025,18925948821,4201708281505422337,300,2017/8/28 15:05,11,108,216
5026,18925948821,4201708281710323781,600,2017/8/28 17:10,11,216,6008
5027,18927205899,4201708101821178823,600,2017/8/10 18:21,11,6008,306
5028,18974997477,4201707201618265930,800,2017/7/20 16:18,11,707,223
5029,18974997477,4201707201755096012,400,2017/7/20 17:55,11,223,3004
5030,18974997477,4201707211241096542,400,2017/7/21 12:41,11,707,701

In [19]:
phone = pd.read_csv("./data/phone.csv")

In [20]:
phone

           mobile province city operator
0     13005188770       广东   广州     中国联通
1     13016089516       广东   广州     中国联通
2     13022033307       广东   广州     中国联通
3     13046202915       广东   湛江     中国联通
4     13049622429       广东   广州     中国联通
5     13066325666       广东   广州     中国联通
6     13071865367       浙江   杭州     中国联通
7     13076787499       广东   广州     中国联通
8     13078232557       广东   湛江     中国联通
9     13078443937       广东   佛山     中国联通
10    13078497171       广东   佛山     中国联通
11    13102065595       天津   天津     中国联通
12    13104881688       广东   广州     中国联通
13    13106673377       广东   佛山     中国联通
14    13112263192       广东   广州     中国联通
15    13112799730       广东   佛山     中国联通
16    13112900326       广东   中山     中国联通
17    13113322094       广东   广州     中国联通
18    13113719569       广东   佛山     中国联通
19    13118853648       广东   佛山     中国联通
20    13118859162       广东   佛山     中国联通
21    13119597204       广东   广州     中国联通
22    13128213868       广东   广州     中国联通
23    13128283850       广东   广州     中国联通
24    13128352432       广东   揭阳     中国联通
25    13129169548       广东   佛山     中国联通
26    13138472322       广东   广州     中国联通
27    13142097799       湖南   长沙     中国联通
28    13143395040       广东   广州     中国联通
29    13143588978       广东   佛山     中国联通
...           ...      ...  ...      ...
1610  13536833416       广东   汕头     中国移动
1611  13826091023       广东   广州     中国移动
1612  18102208900       广东   广州     中国电信
1613  17620066779       广东   广州     中国联通
1614  13609035271       广东   广州     中国移动
1615  15113825184       广东   广州     中国移动
1616  13533204675       广东   广州     中国移动
1617  13902327445       广东   广州     中国移动
1618  13450385573       广东   广州     中国移动
1619  15116176305       湖南   长沙     中国移动
1620  15622305238       广东   广州     中国联通
1621  15018792978       广东   广州     中国移动
1622  13822163501       广东   广州     中国移动
1623  15709381817       甘肃   天水     中国移动
1624  13112138162       广东   揭阳     中国联通
1625  13265912413       广东   广州     中国联通
1626  13538899262       广东   广州     中国移动
1627  15818872307       广东   广州     中国移动
1628  13668925076       广东   广州     中国移动
1629  18702093973       广东   广州     中国移动
1630  13560214023       广东   广州     中国移动
1631  13922135187       广东   广州     中国移动
1632  13202513211       广东   广州     中国联通
1633  15219717595       广东   梅州     中国移动
1634  13710627785       广东   广州     中国移动
1635  15800036217       广东   广州     中国移动
1636  13711048179       广东   广州     中国移动
1637  15013383279       广东   广州     中国移动
1638  18819424695       广东   广州     中国移动
1639  15814874835       广东   广州     中国移动

[1640 rows x 4 columns]

In [23]:
phone.rename({"mobile":"phone"}, inplace=True)

In [24]:
phone

           mobile province city operator
0     13005188770       广东   广州     中国联通
1     13016089516       广东   广州     中国联通
2     13022033307       广东   广州     中国联通
3     13046202915       广东   湛江     中国联通
4     13049622429       广东   广州     中国联通
5     13066325666       广东   广州     中国联通
6     13071865367       浙江   杭州     中国联通
7     13076787499       广东   广州     中国联通
8     13078232557       广东   湛江     中国联通
9     13078443937       广东   佛山     中国联通
10    13078497171       广东   佛山     中国联通
11    13102065595       天津   天津     中国联通
12    13104881688       广东   广州     中国联通
13    13106673377       广东   佛山     中国联通
14    13112263192       广东   广州     中国联通
15    13112799730       广东   佛山     中国联通
16    13112900326       广东   中山     中国联通
17    13113322094       广东   广州     中国联通
18    13113719569       广东   佛山     中国联通
19    13118853648       广东   佛山     中国联通
20    13118859162       广东   佛山     中国联通
21    13119597204       广东   广州     中国联通
22    13128213868       广东   广州     中国联通
23    13128283850       广东   广州     中国联通
24    13128352432       广东   揭阳     中国联通
25    13129169548       广东   佛山     中国联通
26    13138472322       广东   广州     中国联通
27    13142097799       湖南   长沙     中国联通
28    13143395040       广东   广州     中国联通
29    13143588978       广东   佛山     中国联通
...           ...      ...  ...      ...
1610  13536833416       广东   汕头     中国移动
1611  13826091023       广东   广州     中国移动
1612  18102208900       广东   广州     中国电信
1613  17620066779       广东   广州     中国联通
1614  13609035271       广东   广州     中国移动
1615  15113825184       广东   广州     中国移动
1616  13533204675       广东   广州     中国移动
1617  13902327445       广东   广州     中国移动
1618  13450385573       广东   广州     中国移动
1619  15116176305       湖南   长沙     中国移动
1620  15622305238       广东   广州     中国联通
1621  15018792978       广东   广州     中国移动
1622  13822163501       广东   广州     中国移动
1623  15709381817       甘肃   天水     中国移动
1624  13112138162       广东   揭阳     中国联通
1625  13265912413       广东   广州     中国联通
1626  13538899262       广东   广州     中国移动
1627  15818872307       广东   广州     中国移动
1628  13668925076       广东   广州     中国移动
1629  18702093973       广东   广州     中国移动
1630  13560214023       广东   广州     中国移动
1631  13922135187       广东   广州     中国移动
1632  13202513211       广东   广州     中国联通
1633  15219717595       广东   梅州     中国移动
1634  13710627785       广东   广州     中国移动
1635  15800036217       广东   广州     中国移动
1636  13711048179       广东   广州     中国移动
1637  15013383279       广东   广州     中国移动
1638  18819424695       广东   广州     中国移动
1639  15814874835       广东   广州     中国移动

[1640 rows x 4 columns]