In [2]:
import pandas as pd

数据：648个用户的5031条购票记录, 
天气：
    雷阵雨     2093
    多云      1052
    晴        894
    中雨       619
    大雨       180
    大到暴雨     143
    暴雨        50

省份：
    广东    4437
    湖南     176
    浙江      84
    广西      73
    四川      47
    江西      43
    北京      40
    湖北      39
    河南      27
    新疆      13
    海南      10
    天津      10
    山东       6
    河北       6
    安徽       5
    重庆       4
    江苏       3
    辽宁       3
    山西       3
    云南       1
    福建       1

城市：共69个

In [6]:
"""
trade_record = pd.read_csv("./data/trade_record.csv")
trade_valid = trade_record[trade_record["status"] == 11]
trade_valid.drop(["status"], axis=1)
trade_valid.to_csv("./data/trade_valid.csv", index=False)

data = pd.read_csv("./data/trade_valid.csv")
phone = pd.read_csv("./data/phone.csv")
phone.rename(columns={"mobile":"phone"}, inplace=True)
data = data.merge(phone, on="phone", how='inner')
data['date'] = data['time'].apply(lambda x: x.split(' ')[0])
data['hour'] = data['time'].apply(lambda x: x.split(' ')[1].split(':')[0])
data['month'] = data['date'].apply(lambda x: x.split('/')[1])
data['day'] = data['date'].apply(lambda x: x.split('/')[2])
weather = pd.read_csv("./data/weather_2017.csv", names=['date', 'high', 'low', 'weather', 'wind', 'speed'])
weather['month'] = weather['date'].apply(lambda x: str(int(x.split('-')[1])))
weather['day'] = weather['date'].apply(lambda x: str(int(x.split('-')[2])))
weather.drop(['date'], axis=1, inplace=True)
final = data.merge(weather, on=['month', 'day'], how='inner')
final['speed'] = final['speed'].apply(lambda x: x[0:1])

data = final
data['islocal'] = data['city'].apply(lambda x: 1 if x == "广州" else 0)
start = data.groupby('start').size()
start_d = pd.DataFrame()
start_d['start'] = start.index
start_d['start_cnt'] = start.values
stop = data.groupby('stop').size()
stop_d = pd.DataFrame()
stop_d['stop'] = stop.index
stop_d['stop_cnt'] = stop.values
tmp = data.merge(start_d, on="start", how='inner')
tmp = tmp.merge(stop_d, on="stop", how='inner')
tmp['speed'] = tmp['speed'].apply(lambda x: "0" if x == "微" else x)
tmp.to_csv("./data/feature.csv", index=False)

data = pd.read_csv("./data/feature.csv")
def gen_station_map(data):
    station_map = {}
    start_stations = list(data['start'].value_counts().index)
    for start in start_stations:
        stop_stations = list(data['stop'][data['start'] == start].value_counts().index)
        station_map[start] = stop_stations
    return station_map
station_map = gen_station_map(data)
def row_expand(data, station_map):
    tmp = []
    for index, row in data.iterrows():
        station_list = station_map[row['start']]
        real_stop = row['stop']
        for s in station_list:
            row['stop'] = s
            if s == real_stop:
                row['label'] = 1
            else:
                row['label'] = 0
            tmp.append(row)
    result = pd.DataFrame()
    result = result.append(tmp)
    return result
res = row_expand(data, station_map)
res.to_csv("./data/feature_expand.csv", index=False)
"""

In [4]:
trade_record = pd.read_csv("./data/trade_record.csv")
trade_record

,phone,order_id,price,time,status,start,stop
0,13005188770,4201707171955223566,200,2017/7/17 19:55,3,305,306
1,13005188770,4201708011815108607,300,2017/8/1 18:15,10,209,505
2,13016089516,4201707041824363786,300,2017/7/4 18:24,11,216,210
3,13016089516,4201707091450427038,200,2017/7/9 14:50,11,216,218
4,13016089516,4201707091748057253,400,2017/7/9 17:48,11,218,210
5,13016089516,4201707092008567391,300,2017/7/9 20:08,11,215,210
6,13016089516,4201707131051370033,600,2017/7/13 10:51,11,215,410
7,13016089516,4201707132159260564,300,2017/7/13 21:59,11,210,215
8,13016089516,4201707141253090863,300,2017/7/14 12:53,11,215,510
9,13016089516,4201707141752321129,300,2017/7/14 17:52,11,510,506
10,13016089516,4201707151141141562,300,2017/7/15 11:41,11,215,210
11,13016089516,4201707151616131739,300,2017/7/15 16:16,11,210,215
12,13016089516,4201707161503192485,200,2017/7/16 15:03,11,214,215
13,13016089516,4201707171138503122,300,2017/7/17 11:38,11,215,210
14,13016089516,4201707171932053542,300,2017/7/17 19:32,11,210,215
15,13016089516,4201707210812166337,300,2017/7/21 8:12,11,215,211
16,13016089516,4201707211615516708,300,2017/7/21 16:15,11,611,215
17,13016089516,4201707220851037139,300,2017/7/22 8:51,11,215,211
18,13016089516,4201707222213507942,300,2017/7/22 22:13,11,210,215
19,13016089516,4201707241500409252,300,2017/7/24 15:00,11,215,608
20,13016089516,4201707261410281033,300,2017/7/26 14:10,11,215,211
21,13016089516,4201707261711471223,500,2017/7/26 17:11,11,408,215
22,13016089516,4201707271710291987,200,2017/7/27 17:10,11,214,215
23,13016089516,4201708021003003663,300,2017/8/2 10:03,11,215,210
24,13016089516,4201708081937450138,300,2017/8/8 19:37,11,305,109
25,13022033307,4201707021838292655,300,2017/7/2 18:38,11,216,105
26,13022033307,4201707070839035164,400,2017/7/7 8:39,11,216,513
27,13022033307,4201707071937295591,200,2017/7/7 19:37,11,513,303
28,13022033307,4201707200841055514,400,2017/7/20 8:41,11,216,513
29,13022033307,4201707201900496090,200,2017/7/20 19:00,3,513,512
...,...,...,...,...,...,...,...
5297,18925610291,4201707311130145105,700,2017/7/31 11:30,11,631,241
5298,18925610291,4201707311540316926,600,2017/7/31 15:40,11,209,524
5299,18925610291,4201708081648037826,600,2017/8/8 16:48,11,524,507
5300,18925610291,4201708082053320855,700,2017/8/8 20:53,11,506,524
5301,18925610291,4201708101636137559,600,2017/8/10 16:36,11,524,109
5302,18925610291,4201708101944289924,300,2017/8/10 19:44,11,109,303
5303,18925948821,4201708011829098829,200,2017/8/1 18:29,11,6008,6011
5304,18925948821,4201708011932489697,200,2017/8/1 19:32,11,6011,6008
5305,18925948821,4201708032037299757,200,2017/8/3 20:37,11,6008,6007
5306,18925948821,4201708041727577495,200,2017/8/4 17:27,11,6008,6011
5307,18925948821,4201708041923009183,200,2017/8/4 19:23,11,6011,6008
5308,18925948821,4201708121655537293,200,2017/8/12 16:55,11,6011,6008
5309,18925948821,4201708141210385403,200,2017/8/14 12:10,11,6011,6008
5310,18925948821,4201708172111480306,200,2017/8/17 21:11,11,6008,6011
5311,18925948821,4201708172159110661,200,2017/8/17 21:59,11,6011,6008
5312,18925948821,4201708211141495490,700,2017/8/21 11:41,11,6007,408
5313,18925948821,4201708211651078540,500,2017/8/21 16:51,11,108,517
5314,18925948821,4201708221422346671,200,2017/8/22 14:22,11,6011,6008
5315,18925948821,4201708221941330292,500,2017/8/22 19:41,11,106,6008
5316,18925948821,4201708250726339185,600,2017/8/25 7:26,11,6008,108
5317,18925948821,4201708251756456097,500,2017/8/25 17:56,11,108,6011
5318,18925948821,4201708252140408674,200,2017/8/25 21:40,11,6011,6008
5319,18925948821,4201708261217592620,200,2017/8/26 12:17,11,6008,6011
5320,18925948821,4201708280702307711,600,2017/8/28 7:02,11,6008,108
5321,18925948821,4201708281505422337,300,2017/8/28 15:05,11,108,216
5322,18925948821,4201708281710323781,600,2017/8/28 17:10,11,216,6008
5323,18927205899,4201708101821178823,600,2017/8/10 18:21,11,6008,306
5324,18974997477,4201707201618265930,800,2017/7/20 16:18,11,707,223
5325,18974997477,4201707201755096012,400,2017/7/20 17:55,11,223,3004
5326,18974997477,4201707211241096542,400,2017/7/21 12:41,11,707,701